// server/seedAllSacredSites.js
require("dotenv").config();
const mongoose = require("mongoose");

const Site = require("./src/models/Site");
const User = require("./src/models/User");

const allSacredSites = [
  // ==================== MAIN SACRED SITES (1-10) ====================
  {
    name: "Сулайман-Тоо",
    description: "Священная гора, объект Всемирного наследия ЮНЕСКО.",
    location: {
      type: "Point",
      coordinates: [72.789, 40.528],
      address: "г. Ош",
      region: "Ошская область",
      country: "Кыргызстан",
    },
    culturalPeriod: "Ancient",
    heritageStatus: "UNESCO",
    siteType: "sacred",
    sacredType: "mountain",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["гора", "ЮНЕСКО", "Ош"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Саймалуу-Таш",
    description: "Галерея петроглифов (II тыс. до н.э. — VIII в. н.э.).",
    location: {
      type: "Point",
      coordinates: [73.5, 41.2],
      address: "Ферганский хребет",
      region: "Джалал-Абадская область",
      country: "Кыргызстан",
    },
    culturalPeriod: "Prehistoric",
    heritageStatus: "National",
    siteType: "petroglyph",
    sacredType: "petroglyph",
    accessibility: "Restricted",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["петроглифы", "Джалал-Абад"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Башня Бурана",
    description: "Минарет X века на Великом Шелковом пути.",
    location: {
      type: "Point",
      coordinates: [75.25, 42.75],
      address: "12 км от Токмока",
      region: "Чуйская область",
      country: "Кыргызстан",
    },
    culturalPeriod: "Medieval",
    heritageStatus: "National",
    siteType: "archaeological",
    sacredType: "other",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["башня", "Шелковый путь", "Чуй"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Таш-Рабат",
    description: "Древний караван-сарай XV века.",
    location: {
      type: "Point",
      coordinates: [75.8, 40.8],
      address: "Ат-Башинский район",
      region: "Нарынская область",
      country: "Кыргызстан",
    },
    culturalPeriod: "Medieval",
    heritageStatus: "National",
    siteType: "archaeological",
    sacredType: "other",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["караван-сарай", "Нарын"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Озеро Иссык-Куль",
    description: "Одно из крупнейших горных озер мира.",
    location: {
      type: "Point",
      coordinates: [77.0, 42.4],
      address: "Иссык-Кульская котловина",
      region: "Иссык-Кульская область",
      country: "Кыргызстан",
    },
    culturalPeriod: "Unknown",
    heritageStatus: "National",
    siteType: "natural",
    sacredType: "mountain",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["озеро", "Иссык-Куль"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Шах-Фазиль (Сафед-Булан)",
    description: "Историко-мемориальный комплекс XI века.",
    location: {
      type: "Point",
      coordinates: [71.5, 41.1],
      address: "Ала-Букинский район",
      region: "Джалал-Абадская область",
      country: "Кыргызстан",
    },
    culturalPeriod: "Medieval",
    heritageStatus: "National",
    siteType: "sacred",
    sacredType: "mazar",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["мазар", "ислам", "Джалал-Абад"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Манжыл-Ата",
    description: "Долина семи святых родников.",
    location: {
      type: "Point",
      coordinates: [77.0, 42.1],
      address: "Тонский район",
      region: "Иссык-Кульская область",
      country: "Кыргызстан",
    },
    culturalPeriod: "Unknown",
    heritageStatus: "Regional",
    siteType: "sacred",
    sacredType: "spring",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["источники", "исцеление", "Иссык-Куль"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Таштар-Ата",
    description: "Гора в предгорьях Бишкека.",
    location: {
      type: "Point",
      coordinates: [74.5, 42.9],
      address: "Предгорья Бишкека",
      region: "Чуйская область",
      country: "Кыргызстан",
    },
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "mountain",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["гора", "исцеление", "Чуй"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Гумбез Манаса",
    description: "Мавзолей, связанный с эпосом «Манас».",
    location: {
      type: "Point",
      coordinates: [72.2, 42.5],
      address: "Таласская область",
      region: "Таласская область",
      country: "Кыргызстан",
    },
    culturalPeriod: "Medieval",
    heritageStatus: "National",
    siteType: "sacred",
    sacredType: "mazar",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["Манас", "мавзолей", "Талас"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Абшир-Ата",
    description: "«Молочный» водопад и святые источники.",
    location: {
      type: "Point",
      coordinates: [72.6, 40.3],
      address: "Ноокатский район",
      region: "Ошская область",
      country: "Кыргызстан",
    },
    culturalPeriod: "Unknown",
    heritageStatus: "Regional",
    siteType: "sacred",
    sacredType: "spring",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["водопад", "источник", "Ош"],
    mainPhoto: "",
    photoUrls: [],
  },

  // ==================== NATURAL SACRED OBJECTS (11-25) ====================
  {
    name: "Нылды-Ата",
    location: {
      type: "Point",
      coordinates: [72.3, 42.4],
      region: "Таласская область",
      country: "Кыргызстан",
    },
    description: "Комплекс из 22 сакральных объектов.",
    culturalPeriod: "Unknown",
    heritageStatus: "Regional",
    siteType: "sacred",
    sacredType: "spring",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["источник", "Талас"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Петроглифы Чолпон-Аты",
    location: {
      type: "Point",
      coordinates: [77.1, 42.6],
      region: "Иссык-Кульская область",
      country: "Кыргызстан",
    },
    description: "Древние наскальные рисунки.",
    culturalPeriod: "Prehistoric",
    heritageStatus: "National",
    siteType: "petroglyph",
    sacredType: "petroglyph",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["петроглифы", "Иссык-Куль"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Ала-Арча",
    location: {
      type: "Point",
      coordinates: [74.4, 42.6],
      region: "Чуйская область",
      country: "Кыргызстан",
    },
    description: "Национальный парк.",
    culturalPeriod: "Unknown",
    heritageStatus: "National",
    siteType: "natural",
    sacredType: "mountain",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["парк", "Чуй"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Пещера Чакка-Тамар",
    location: {
      type: "Point",
      coordinates: [72.79, 40.53],
      region: "Ошская область",
      country: "Кыргызстан",
    },
    description: "Пещера на Сулайман-Тоо.",
    culturalPeriod: "Unknown",
    heritageStatus: "UNESCO",
    siteType: "sacred",
    sacredType: "cave",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["пещера", "Ош"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Пещера Руша-Ункур",
    location: {
      type: "Point",
      coordinates: [72.79, 40.53],
      region: "Ошская область",
      country: "Кыргызстан",
    },
    description: "Самая большая пещера на Сулайман-Тоо.",
    culturalPeriod: "Unknown",
    heritageStatus: "UNESCO",
    siteType: "sacred",
    sacredType: "cave",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["пещера", "Ош"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Арча-Мазар",
    location: {
      type: "Point",
      coordinates: [72.8, 41.5],
      region: "Джалал-Абадская область",
      country: "Кыргызстан",
    },
    description: "Священная гора.",
    culturalPeriod: "Ancient",
    heritageStatus: "Regional",
    siteType: "sacred",
    sacredType: "mountain",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["гора", "Джалал-Абад"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Родник Майтик Дубана",
    location: {
      type: "Point",
      coordinates: [77.0, 42.1],
      region: "Иссык-Кульская область",
      country: "Кыргызстан",
    },
    description: "Один из семи святых родников.",
    culturalPeriod: "Unknown",
    heritageStatus: "Regional",
    siteType: "sacred",
    sacredType: "spring",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["родник"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Родник Илим",
    location: {
      type: "Point",
      coordinates: [77.0, 42.1],
      region: "Иссык-Кульская область",
      country: "Кыргызстан",
    },
    description: "Родник мудрости.",
    culturalPeriod: "Unknown",
    heritageStatus: "Regional",
    siteType: "sacred",
    sacredType: "spring",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["родник"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Родник Бала",
    location: {
      type: "Point",
      coordinates: [77.0, 42.1],
      region: "Иссык-Кульская область",
      country: "Кыргызстан",
    },
    description: "Родник для бездетных пар.",
    culturalPeriod: "Unknown",
    heritageStatus: "Regional",
    siteType: "sacred",
    sacredType: "spring",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["родник"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Родник Бугу Энэ",
    location: {
      type: "Point",
      coordinates: [77.0, 42.1],
      region: "Иссык-Кульская область",
      country: "Кыргызстан",
    },
    description: "Родник Матери-Оленихи.",
    culturalPeriod: "Unknown",
    heritageStatus: "Regional",
    siteType: "sacred",
    sacredType: "spring",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["родник"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Родник Азиз Булагы",
    location: {
      type: "Point",
      coordinates: [77.0, 42.1],
      region: "Иссык-Кульская область",
      country: "Кыргызстан",
    },
    description: "Священный змеиный родник.",
    culturalPeriod: "Unknown",
    heritageStatus: "Regional",
    siteType: "sacred",
    sacredType: "spring",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["родник"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Родник Уй Булоо",
    location: {
      type: "Point",
      coordinates: [77.0, 42.1],
      region: "Иссык-Кульская область",
      country: "Кыргызстан",
    },
    description: "Родник семейного благополучия.",
    culturalPeriod: "Unknown",
    heritageStatus: "Regional",
    siteType: "sacred",
    sacredType: "spring",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["родник"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Гора Спасения",
    location: {
      type: "Point",
      coordinates: [74.5, 42.9],
      region: "Чуйская область",
      country: "Кыргызстан",
    },
    description: "Рукотворный курган.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "mountain",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["гора", "Чуй"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Камень плодородия",
    location: {
      type: "Point",
      coordinates: [71.5, 41.1],
      region: "Джалал-Абадская область",
      country: "Кыргызстан",
    },
    description: "Камень, помогающий женщинам.",
    culturalPeriod: "Medieval",
    heritageStatus: "National",
    siteType: "sacred",
    sacredType: "other",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["камень"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Кыргын мечет",
    location: {
      type: "Point",
      coordinates: [71.5, 41.1],
      region: "Джалал-Абадская область",
      country: "Кыргызстан",
    },
    description: "Мечеть в память о резне.",
    culturalPeriod: "Medieval",
    heritageStatus: "National",
    siteType: "sacred",
    sacredType: "mazar",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["мечеть"],
    mainPhoto: "",
    photoUrls: [],
  },

  // ==================== MAZARS (26-35) ====================
  {
    name: "Мазар Булан",
    location: {
      type: "Point",
      coordinates: [71.5, 41.1],
      region: "Джалал-Абадская область",
      country: "Кыргызстан",
    },
    description: "Мавзолей девушки Булан.",
    culturalPeriod: "Medieval",
    heritageStatus: "National",
    siteType: "sacred",
    sacredType: "mazar",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["мазар"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Мазар Шах-Джарира",
    location: {
      type: "Point",
      coordinates: [71.5, 41.1],
      region: "Джалал-Абадская область",
      country: "Кыргызстан",
    },
    description: "Захоронение внука пророка.",
    culturalPeriod: "Medieval",
    heritageStatus: "National",
    siteType: "sacred",
    sacredType: "mazar",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["мазар"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Христианский монастырь",
    location: {
      type: "Point",
      coordinates: [77.0, 42.5],
      region: "Иссык-Кульская область",
      country: "Кыргызстан",
    },
    description: "Место хранения мощей апостола Матфея.",
    culturalPeriod: "Medieval",
    heritageStatus: "Unprotected",
    siteType: "sacred",
    sacredType: "other",
    accessibility: "Unknown",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["монастырь"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Часовни на Таштар-Ата",
    location: {
      type: "Point",
      coordinates: [74.5, 42.9],
      region: "Чуйская область",
      country: "Кыргызстан",
    },
    description: "Часовни четырех религий.",
    culturalPeriod: "Modern",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "other",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["часовни"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Древнее городище Баласагун",
    location: {
      type: "Point",
      coordinates: [75.25, 42.75],
      region: "Чуйская область",
      country: "Кыргызстан",
    },
    description: "Столица Караханидов.",
    culturalPeriod: "Medieval",
    heritageStatus: "National",
    siteType: "archaeological",
    sacredType: "other",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["городище"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Мечеть на Сулайман-Тоо",
    location: {
      type: "Point",
      coordinates: [72.79, 40.53],
      region: "Ошская область",
      country: "Кыргызстан",
    },
    description: "Мечеть XVI века.",
    culturalPeriod: "Medieval",
    heritageStatus: "UNESCO",
    siteType: "sacred",
    sacredType: "mazar",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["мечеть"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Свято-Троицкая церковь",
    location: {
      type: "Point",
      coordinates: [78.4, 42.5],
      region: "Иссык-Кульская область",
      country: "Кыргызстан",
    },
    description: "Собор 1895 года в Караколе.",
    culturalPeriod: "Modern",
    heritageStatus: "Regional",
    siteType: "sacred",
    sacredType: "other",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["церковь"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Церковь Покрова",
    location: {
      type: "Point",
      coordinates: [77.5, 42.7],
      region: "Иссык-Кульская область",
      country: "Кыргызстан",
    },
    description: "Церковь в с. Григорьевка.",
    culturalPeriod: "Modern",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "other",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["церковь"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Мазар Таксо-Ата",
    location: {
      type: "Point",
      coordinates: [74.8, 42.8],
      region: "Чуйская область",
      country: "Кыргызстан",
    },
    description: "Священное захоронение.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "mazar",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["мазар"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Мазар Мамбет-Али-Пишен",
    location: {
      type: "Point",
      coordinates: [74.9, 42.9],
      region: "Чуйская область",
      country: "Кыргызстан",
    },
    description: "Место паломничества.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "mazar",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["мазар"],
    mainPhoto: "",
    photoUrls: [],
  },

  // ==================== SACRED TREES (36-45) ====================
  {
    name: "Святое дерево Кош-Коргон",
    location: {
      type: "Point",
      coordinates: [74.5, 42.8],
      region: "Чуйская область",
      country: "Кыргызстан",
    },
    description: "Почитаемое дерево.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "tree",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["дерево"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Дерево-долгожитель Бель-Болчок",
    location: {
      type: "Point",
      coordinates: [74.6, 42.7],
      region: "Чуйская область",
      country: "Кыргызстан",
    },
    description: "Древнее дерево.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "tree",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["дерево"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Святая арча Чон-Ак-Суу",
    location: {
      type: "Point",
      coordinates: [75.5, 41.5],
      region: "Нарынская область",
      country: "Кыргызстан",
    },
    description: "Священный можжевельник.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "tree",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["арча"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Дерево-целитель Эпкин",
    location: {
      type: "Point",
      coordinates: [75.0, 42.5],
      region: "Чуйская область",
      country: "Кыргызстан",
    },
    description: "Целебное дерево.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "tree",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["дерево"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Святое дерево Кара-Тейит",
    location: {
      type: "Point",
      coordinates: [72.3, 42.5],
      region: "Таласская область",
      country: "Кыргызстан",
    },
    description: "Дерево у мазара.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "tree",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["дерево"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Дерево Чолок-Кайын",
    location: {
      type: "Point",
      coordinates: [75.8, 41.3],
      region: "Нарынская область",
      country: "Кыргызстан",
    },
    description: "Дерево с ленточками.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "tree",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["дерево"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Арча Талдык",
    location: {
      type: "Point",
      coordinates: [75.6, 41.2],
      region: "Нарынская область",
      country: "Кыргызстан",
    },
    description: "Священная арча.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "tree",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["арча"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Дерево Кок-Булак",
    location: {
      type: "Point",
      coordinates: [74.3, 42.9],
      region: "Чуйская область",
      country: "Кыргызстан",
    },
    description: "Дерево у источника.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "tree",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["дерево"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Святая ива Мамбет-Али",
    location: {
      type: "Point",
      coordinates: [74.9, 42.9],
      region: "Чуйская область",
      country: "Кыргызстан",
    },
    description: "Священная ива.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "tree",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["ива"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Дерево-хранитель Кайырма",
    location: {
      type: "Point",
      coordinates: [72.4, 42.3],
      region: "Таласская область",
      country: "Кыргызстан",
    },
    description: "Дерево-хранитель.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "tree",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["дерево"],
    mainPhoto: "",
    photoUrls: [],
  },

  // ==================== SACRED SPRINGS (46-55) ====================
  {
    name: "Родник Кара-Суу",
    location: {
      type: "Point",
      coordinates: [74.7, 42.6],
      region: "Чуйская область",
      country: "Кыргызстан",
    },
    description: "Святой родник.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "spring",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["родник"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Источник Ак-Суу",
    location: {
      type: "Point",
      coordinates: [78.5, 42.5],
      region: "Иссык-Кульская область",
      country: "Кыргызстан",
    },
    description: "Целебный источник.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "spring",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["родник"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Родник Айгыр-Джал",
    location: {
      type: "Point",
      coordinates: [74.4, 42.5],
      region: "Чуйская область",
      country: "Кыргызстан",
    },
    description: "Святой родник.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "spring",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["родник"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Источник Кек-Булак",
    location: {
      type: "Point",
      coordinates: [74.3, 42.9],
      region: "Чуйская область",
      country: "Кыргызстан",
    },
    description: "Святой источник.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "spring",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["родник"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Родник Чолок-Кайын",
    location: {
      type: "Point",
      coordinates: [75.8, 41.3],
      region: "Нарынская область",
      country: "Кыргызстан",
    },
    description: "Святой родник.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "spring",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["родник"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Родник Байгельды-Ата",
    location: {
      type: "Point",
      coordinates: [74.5, 42.7],
      region: "Чуйская область",
      country: "Кыргызстан",
    },
    description: "Родник у мазара.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "spring",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["родник"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Родник Байбол-Ата",
    location: {
      type: "Point",
      coordinates: [72.5, 42.3],
      region: "Таласская область",
      country: "Кыргызстан",
    },
    description: "Святой родник.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "spring",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["родник"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Источник Асан-Ата",
    location: {
      type: "Point",
      coordinates: [74.6, 42.8],
      region: "Чуйская область",
      country: "Кыргызстан",
    },
    description: "Источник у мазара.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "spring",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["родник"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Родник Кара-Булак",
    location: {
      type: "Point",
      coordinates: [75.4, 41.4],
      region: "Нарынская область",
      country: "Кыргызстан",
    },
    description: "Святой родник.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "spring",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["родник"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Родник Кен-Булун",
    location: {
      type: "Point",
      coordinates: [77.3, 42.2],
      region: "Иссык-Кульская область",
      country: "Кыргызстан",
    },
    description: "Святой родник.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "spring",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["родник"],
    mainPhoto: "",
    photoUrls: [],
  },

  // ==================== STONES (56-65) ====================
  {
    name: "Камень-следопыт",
    location: {
      type: "Point",
      coordinates: [74.8, 42.6],
      region: "Чуйская область",
      country: "Кыргызстан",
    },
    description: "Камень с отпечатком копыта.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "other",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["камень"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Скала Голова дракона",
    location: {
      type: "Point",
      coordinates: [75.3, 41.6],
      region: "Нарынская область",
      country: "Кыргызстан",
    },
    description: "Скала в форме головы дракона.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "other",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["скала"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Камень желаний",
    location: {
      type: "Point",
      coordinates: [74.5, 42.8],
      region: "Чуйская область",
      country: "Кыргызстан",
    },
    description: "Камень, исполняющий желания.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "other",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["камень"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Скала Манас-Таш",
    location: {
      type: "Point",
      coordinates: [72.2, 42.5],
      region: "Таласская область",
      country: "Кыргызстан",
    },
    description: "Скала, связанная с Манасом.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "other",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["скала"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Камень Кочкор",
    location: {
      type: "Point",
      coordinates: [75.5, 42.2],
      region: "Нарынская область",
      country: "Кыргызстан",
    },
    description: "Камень с петроглифами.",
    culturalPeriod: "Prehistoric",
    heritageStatus: "Local",
    siteType: "petroglyph",
    sacredType: "petroglyph",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["петроглифы"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Камень-чаша",
    location: {
      type: "Point",
      coordinates: [74.7, 42.5],
      region: "Чуйская область",
      country: "Кыргызстан",
    },
    description: "Камень для сбора воды.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "other",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["камень"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Седло Манаса",
    location: {
      type: "Point",
      coordinates: [72.3, 42.4],
      region: "Таласская область",
      country: "Кыргызстан",
    },
    description: "Валун в форме седла.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "other",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["валун"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Камни-великаны Жети-Огуз",
    location: {
      type: "Point",
      coordinates: [78.3, 42.3],
      region: "Иссык-Кульская область",
      country: "Кыргызстан",
    },
    description: "Огромные камни.",
    culturalPeriod: "Unknown",
    heritageStatus: "Regional",
    siteType: "natural",
    sacredType: "other",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["камни"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Скала Долон",
    location: {
      type: "Point",
      coordinates: [75.7, 41.8],
      region: "Нарынская область",
      country: "Кыргызстан",
    },
    description: "Святая скала на перевале.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "other",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["скала"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Камень с ладонью",
    location: {
      type: "Point",
      coordinates: [74.9, 42.7],
      region: "Чуйская область",
      country: "Кыргызстан",
    },
    description: "Камень с отпечатком ладони.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "other",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["камень"],
    mainPhoto: "",
    photoUrls: [],
  },

  // ==================== COMPLEXES (66-70) ====================
  {
    name: "Мазар Шырдак-Бек",
    location: {
      type: "Point",
      coordinates: [74.8, 42.9],
      region: "Чуйская область",
      country: "Кыргызстан",
    },
    description: "Священный мазар.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "mazar",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["мазар"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Комплекс Ордо",
    location: {
      type: "Point",
      coordinates: [75.6, 41.5],
      region: "Нарынская область",
      country: "Кыргызстан",
    },
    description: "Сакральная зона.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "other",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["комплекс"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Мазар Кара-Кече",
    location: {
      type: "Point",
      coordinates: [72.4, 42.2],
      region: "Таласская область",
      country: "Кыргызстан",
    },
    description: "Священный мазар.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "mazar",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["мазар"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Мазар Бек-Бейит",
    location: {
      type: "Point",
      coordinates: [74.7, 42.8],
      region: "Чуйская область",
      country: "Кыргызстан",
    },
    description: "Священный мазар.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "mazar",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["мазар"],
    mainPhoto: "",
    photoUrls: [],
  },
  {
    name: "Чон-Таш",
    location: {
      type: "Point",
      coordinates: [77.2, 42.5],
      region: "Иссык-Кульская область",
      country: "Кыргызстан",
    },
    description: "Святое место.",
    culturalPeriod: "Unknown",
    heritageStatus: "Local",
    siteType: "sacred",
    sacredType: "other",
    accessibility: "Public",
    isVerified: true,
    verificationStatus: "approved",
    tags: ["святое место"],
    mainPhoto: "",
    photoUrls: [],
  },
];

async function seedDatabase() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("✅ Connected to MongoDB");

    let adminUser = await User.findOne({ role: "admin" });
    if (!adminUser) {
      adminUser = await User.create({
        username: "admin",
        email: "admin@amanat.kg",
        password: "Admin123!",
        role: "admin",
        isVerified: true,
      });
      console.log("✅ Created admin user");
    }

    const sitesWithUser = allSacredSites.map((site) => ({
      ...site,
      createdBy: adminUser._id,
    }));

    await Site.deleteMany({
      siteType: { $in: ["sacred", "petroglyph", "natural", "archaeological"] },
    });
    console.log("🗑️ Cleared existing sites");

    const inserted = await Site.insertMany(sitesWithUser);
    console.log(`✅ Successfully inserted ${inserted.length} sacred sites`);
    await Site.collection.createIndex({ location: "2dsphere" });

    console.log("\n✨ All 70 sacred sites imported successfully!");
    process.exit(0);
  } catch (error) {
    console.error("❌ Error:", error.message);
    process.exit(1);
  }
}

seedDatabase();
